Layer_Architecture:
- Layer: Conv2D
  filters: 64
  kernel_size: 5
  activation: relu
- Layer: MaxPool2D
  pool_size: 2
- Layer: Conv2D
  filters: 64
  kernel_size: 5
  activation: relu
- Layer: MaxPool2D
  pool_size: 3
- Layer: Flatten
- Layer: Dropout
  rate: 0.5
- Layer: Dense
  units: 100
  activation: relu
- Layer: Dense
  units: 100
  activation: relu
- Layer: Dropout
  rate: 0.5
- Layer: Dense
  units: 100
  activation: relu
- Layer: Dense
  units: 100
  activation: relu
- Layer: Dense
  units: 10
  activation: softmax
Optimizer:
  Name: Adam
  learning_rate: 0.0006
  beta_1: 0.8
Losses:
  Name: SparseCategoricalCrossentropy
  from_logits: True
